### ISSUE TITLE
大咖，后台可以放出来吗？或者给些指导

### ISSUE THREAD

**Issue by leo20160311** [yigger/jiezhang#10]

**Comment by yigger** [comment]
后台写得比较渣，不好意思放出来，后期我完善一下后考虑放出来~

**Comment by leo20160311** [comment]
可以给出部分接口的出入参说明不，翻译小程序消耗时光。 我是做后台的，我们可以打打配合哈




在 2019-02-23 20:38:50，"yigger" <notifications@github.com> 写道：


后台写得比较渣，不好意思放出来，后期我完善一下后考虑放出来~
