### ISSUE TITLE
API 接口文档

### ISSUE THREAD

**Issue by fallowu** [yigger/jiezhang#17]
你好，可以提供api 接口文档吗

**Comment by yigger** [comment]
还在开发中哦..https://github.com/yigger/JZ-back

**Comment by fallowu** [comment]
> 还在开发中哦..https://github.com/yigger/JZ-back

不是代码哦。就是暴露下前后端对接的接口定义文档，这样可以提供更多版本的可能。

**Comment by yigger** [comment]
哦，明白你意思，不过暂时还没时间弄，我先记下这个需求
