### ISSUE TITLE
日历页面有bug

### ISSUE THREAD

**Issue by Caigengliang** [yigger/jiezhang#4]
点击非当前天数不显示

**Comment by yigger** [comment]
@Caigengliang 能否提供下截图

**Comment by Caigengliang** [comment]
![default](https://user-images.githubusercontent.com/20618898/45604167-54fa8400-ba64-11e8-9457-c5ec2e3838d4.png) 
我点选非当前日期就出现这样的情况。

**Comment by yigger** [comment]
好的，感谢反馈
刚好最近也在构思怎么调整这块
