### ISSUE TITLE
服务器

### ISSUE THREAD

**Issue by oy1994** [yigger/jiezhang#7]

**Comment by oy1994** [comment]
我在github.com上看到了您制作的记账微信小程序，简洁的界面和实用的引索统计功能都吸引了我。本人也是一名德州扑克玩家，一直想找一款好的记账软件用作资金管理。于是想要克隆您的小程序，并稍微更改下界面选项，用作扑克记账，并分享给我的一些朋友（不做商业用途）。

但由于我缺乏相关的知识。目前只能在微信开发工具上运行前端程序。对于云服务器的搭建一窍不通。而在这之前，我已经在腾讯云上购置了云服务器和数据库，个人域名也进行了备案。

我能拜托您在空闲的时候，登录我的云服务器帮我进行相关的设定调试吗？为此，我愿意转您500的支付宝红包，作为对您帮助的感谢！

很感谢您这样无私的将自己的作品公开供大家学习使用，但由于我个人的水平问题，真心希望得到您的帮助！

**Comment by yigger** [comment]
@oy1994  如何联系你呢？
